service: scrapers
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.environment.STAGE}
  region: us-east-2
  profile: eb-cli2
  timeout: 30
  apiKeys:
    - name: ${self:custom.environment.STAGE}-siteKey
  environment:
    MYSQL_HOST: ${self:custom.environment.MYSQL_HOST}
    MYSQL_DATABASE: ${self:custom.environment.MYSQL_DATABASE}
    MYSQL_USERNAME: ${self:custom.environment.MYSQL_USERNAME}
    MYSQL_PASSWORD: ${self:custom.environment.MYSQL_PASSWORD}
    MYSQL_PORT: ${self:custom.environment.MYSQL_PORT}
    SCRAPER_MAX_PAGES: ${self:custom.environment.SCRAPER_MAX_PAGES}
    QUEUE_NAME: ${self:custom.environment.QUEUE_NAME}
    REGION: ${self:custom.environment.REGION}
package:
  individually: true
plugins:
  - serverless-webpack
  - serverless-offline
functions:
  hectvSiteScraper:
    handler: functions/receiver.scrape
    description: Scrapes the websites to populate the events.
    reservedConcurrency: 10
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ${self:custom.environment.QUEUE_NAME}
              - Arn
  hectvSiteQueue:
    handler: functions/sender.queue
    description: Queues new websites to be scraped.
    events:
      - http:
          path: sites/{id}/{page}
          method: post
resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/lambda-access-role.yml)}
  - ${file(resources/simple-queue.yml)}

custom:
  stage: ${self:custom.environment.STAGE}
  environment: ${file(env.yml)}
  webpackIncludeModules:
    packagePath: "./package.json"
  serverless-offline:
    babelOptions:
      presets: ["es2015"]
