service: scrapers
provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.environment.STAGE}
  region: us-east-1
  profile: eb-cli2
  timeout: 30
  vpc:
    securityGroupIds:
      — ${self:custom.environment.SECURITY_GROUP}
  apiKeys:
   - name: ${self:custom.environment.STAGE}-siteKey
  environment:
    MYSQL_HOST: ${self:custom.environment.MYSQL_HOST}
    MYSQL_DATABASE: ${self:custom.environment.MYSQL_DATABASE}
    MYSQL_USERNAME: ${self:custom.environment.MYSQL_USERNAME}
    MYSQL_PASSWORD: ${self:custom.environment.MYSQL_PASSWORD}
    MYSQL_PORT: ${self:custom.environment.MYSQL_PORT}
    SCRAPER_MAX_PAGES: ${self:custom.environment.SCRAPER_MAX_PAGES}
package:
  individually: true
plugins:
  - serverless-webpack
  - serverless-offline
functions:
  hectvSiteScraper:
    handler: api/sites.scrape
    description: Scrapes the websites to populate the events.
    events:
      - http:
          path: sites/{id}/{page}
          method: post
resources:
  - ${file(resources/api-gateway-errors.yml)}
custom:
  stage: ${self:custom.environment.STAGE}
  environment: ${file(env.yml)}
  webpackIncludeModules:
    packagePath: './package.json'
  serverless-offline:
    babelOptions:
      presets: ["es2015"]