Resources:
  AWSLambdaVPCAccessExecutionRole:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Creating policy for vpc connetion.
      Roles:
        - { "Ref": "IamRoleLambdaExecution" }
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - sqs:*
              - ec2:*
              - xray:*
              - rds:*
              - rds-db:*
            Resource: "*"
